visitor draft
shogun-toolbox/shogun pull request #4786
Opened 2019-10-25 12:23 UTC by ktiefe

2019-10-25 12:33 UTC, gf712 commented on src/shogun/base/SGObject.h
> +});
i think the idea is to put this in watch_param? @vigsterkr

2019-10-28 07:02 UTC, vigsterkr requested changes
we need to think about how to deal with arrays

2019-10-28 07:02 UTC, vigsterkr commented on src/shogun/base/SGObject.cpp
> +	auto* result = sgo_details::get_by_tag(this, name);
the problem here that imo this ignores the `index` parameter. so the visitor that you've written only works in the expected manner for `CSGObject::get(std::string_view name, std::nothrow_t)`. i need to see how we support get `CSGObject* CSGObject::get(std::string_view name, index_t index) const`. that's basically when the registered parameter is an array

2019-10-28 07:16 UTC, vigsterkr commented on src/shogun/base/SGObject.h
> +CSGObject* get_by_tag(const CSGObject* obj, std::string_view name) {
this whole thing could be deleted and go into a private function that is implemented in .cpp

2019-10-28 07:17 UTC, vigsterkr commented on src/shogun/base/SGObject.h
> +		if constexpr (is_sg_base<T>::value) {
imo if you wrap this whole block into a constexpr function then you could just call that instead of copy pasting things 4 times.

2019-10-28 07:18 UTC, vigsterkr commented on src/shogun/base/SGObject.h
> +struct InterfaceVisitor
this might be better to place into a separate .h file and include it here. place it under src/shogun/util/visitors

2019-11-09 12:40 UTC, vigsterkr commented
closing in favour of #4793 
sorry @ktiefe needed this fix...

2019-11-09 12:40 UTC, closed without merging