simplified CMakeLists.txt
shogun-toolbox/shogun pull request #4828
Opened 2020-02-18 19:09 UTC by gf712

@vigsterkr added cmake functions to remove some repetition

2020-02-18 19:11 UTC, gf712 commented on src/shogun/mathematics/graph/CMakeLists.txt
> +    )
@vigsterkr no idea if this how cmake_parse_arguments is meant to be used, but it seems to work

2020-02-19 05:50 UTC, vigsterkr requested changes

2020-02-19 05:50 UTC, vigsterkr commented on src/shogun/mathematics/graph/CMakeLists.txt
> +set(${EXECUTORS} "")
this could be a LIST, to which you append: `LIST(APPEND ....`

2020-02-19 09:36 UTC, gf712 commented on src/shogun/mathematics/graph/CMakeLists.txt
> +set(${EXECUTORS} "")
this was the only I found to add things to a variable in the parent scope https://cmake.org/pipermail/cmake/2018-September/068291.html

2020-02-19 09:37 UTC, gf712 commented on src/shogun/mathematics/graph/CMakeLists.txt
> +set(${EXECUTORS} "")
i removed the `set(${EXECUTORS} "")` as it is redundant.. In the function there is `set(EXECUTORS ${EXECUTORS} ${EXECUTOR_NAME} PARENT_SCOPE)`

2020-02-19 10:37 UTC, merged