Update the Windows build section
shogun-toolbox/shogun pull request #4902
Opened 2020-03-09 15:10 UTC by vinnik-dmitry07

Structured building steps, fixed arguments in cmake command, used environment variables to follow the DRY principle, added an output example.

2020-03-09 16:05 UTC, vigsterkr requested changes
great! i'm just not so sure about including the whole cmake listing... this is really a lot of LoC :)
but while you are at it, do you think you could add couple of lines about clcache? we are using it in azure pipelines so from the yaml files you can figure out how it is used. it is very handy when you need to compile shogun couple of times. it's like ccache but for windows.

2020-03-09 18:29 UTC, vinnik-dmitry07 commented
> great! i'm just not so sure about including the whole cmake listing... this is really a lot of LoC :)
> but while you are at it, do you think you could add couple of lines about clcache? we are using it in azure pipelines so from the yaml files you can figure out how it is used. it is very handy when you need to compile shogun couple of times. it's like ccache but for windows.

Should I merely add some mention about it and put this nice [link](https://github.com/frerich/clcache/wiki/Caveats#no-cache-hits-when-building-via-visual-studio-ide-or-msbuild)?

2020-03-09 19:19 UTC, vigsterkr commented
linking it would be more than sufficient thanx!

2020-03-11 16:14 UTC, vigsterkr commented
@vinnik-dmitry07 any update on this? would be great to merge, just the clcache part is missing :)

2020-03-12 17:34 UTC, vinnik-dmitry07 commented
Yes, I have almost completed.

2020-03-12 18:08 UTC, vinnik-dmitry07 commented
That is it.

2020-03-13 08:52 UTC, vigsterkr reviewed
one little typo

2020-03-13 08:52 UTC, vigsterkr commented on doc/readme/INSTALL.md
> +> Be carefull cmake can search out of the build directory to load libraries thus remove other directories that contain the shogun sources
careful

2020-03-13 10:02 UTC, merged