Kernel Constructor Cleanup -- issue 5030
shogun-toolbox/shogun pull request #5136
Opened 2020-12-05 16:02 UTC by GuoxinYin

This is some cleanup trying to fix issue #5030 @

2020-12-07 12:12 UTC, gf712 requested changes
lgtm, just need to remove some whitespaces. Thanks!

2020-12-07 12:12 UTC, gf712 commented on src/shogun/kernel/GaussianShortRealKernel.h
> +
remove whitespace

2020-12-07 12:12 UTC, gf712 commented on src/shogun/kernel/HistogramIntersectionKernel.h
> +
remove whitespace

2020-12-07 12:12 UTC, gf712 commented on src/shogun/kernel/SphericalKernel.h
> +
remove whitespace

2020-12-07 12:12 UTC, gf712 commented on src/shogun/kernel/WeightedDegreeRBFKernel.h
> +
remove whitespace

2020-12-07 12:23 UTC, GuoxinYin commented
Hi @gf712, I have finished removing the whitespaces. Please help review it. Thanks!

2020-12-08 13:33 UTC, merged

2020-12-08 13:33 UTC, gf712 commented
Thanks for this!